HELP(button name,
	button slug,
	button action,
	diablo binding for player 1,
	fremantle binding for player 1)
BUTTON("□", s, P(S), 45, 38)
BUTTON("o", o, P(O), 48, 40)
BUTTON("x", x, P(X), 20, 53)
BUTTON("△", t, P(T), 32, 25)
BUTTON("L1", l1, P(L1), 24, 37)
BUTTON("R1", r1, P(R1), 22, 22)
BUTTON("L2", l2, P(L2), 26, 24)
BUTTON("R2", r2, P(R2), 28, 59)
BUTTON("Start", start, P(START), 65, 65)
BUTTON("Select", select, P(SELECT), 135, 58)
BUTTON("↑", dn, P(UP), 111, 111)
BUTTON("↓", ds, P(DOWN), 116, 116)
BUTTON("←", dw, P(LEFT), 113, 113)
BUTTON("→", de, P(RIGHT), 114, 114)
BUTTON(N_("Return to launcher"), quit, P(QUIT), 9, 50)
LAST
