HELP(button name,
	button slug,
	button action,
	fremantle binding for player 1)
BUTTON("□", s, P(S), 38)
BUTTON("o", o, P(O), 40)
BUTTON("x", x, P(X), 53)
BUTTON("△", t, P(T), 25)
BUTTON("L1", l1, P(L1), 37)
BUTTON("R1", r1, P(R1), 22)
BUTTON("L2", l2, P(L2), 24)
BUTTON("R2", r2, P(R2), 59)
BUTTON("Start", start, P(START), 65)
BUTTON("Select", select, P(SELECT), 58)
BUTTON("↑", dn, P(UP), 111)
BUTTON("↓", ds, P(DOWN), 116)
BUTTON("←", dw, P(LEFT), 113)
BUTTON("→", de, P(RIGHT), 114)
BUTTON(N_("Return to launcher"), quit, P(QUIT), 50)
LAST
