#!/bin/sh
# postinst script for drnokcps2
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
    	gconftool-2 --makefile-install-rule /usr/share/gconf/schemas/psx4all.schemas >/dev/null
	gtk-update-icon-cache -f /usr/share/icons/hicolor
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

